"""Constants for the AirTouch 3 integration."""

from __future__ import annotations

DOMAIN = "airtouch3"

# Network and timing
DEFAULT_PORT = 8899
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_INCLUDE_SENSORS = True
DEFAULT_INCLUDE_ZONES = True
CONNECT_TIMEOUT = 5.0
READ_TIMEOUT = 1.0
MIN_SCAN_INTERVAL = 10
MAX_SCAN_INTERVAL = 300

# Configuration keys
CONF_INCLUDE_SENSORS = "include_sensors"
CONF_INCLUDE_ZONES = "include_zones"

# Message sizes
STATE_MSG_SIZE = 492
INTERNET_MSG_SIZE = 395
COMMAND_MSG_SIZE = 13

# Message fields
MSG_HEADER = 0x55
MSG_LENGTH = 0x0C

# Command identifiers (byte 1)
CMD_INIT = 0x01
CMD_ZONE = 0x81
CMD_AC = 0x86

# AC subcommands (byte 4)
AC_POWER_TOGGLE = 0x80
AC_MODE = 0x81
AC_FAN = 0x82
AC_TEMP_UP = 0xA3
AC_TEMP_DOWN = 0x93

# Zone subcommands (byte 4)
ZONE_TOGGLE = 0x80
ZONE_DAMPER_UP = 0x02
ZONE_DAMPER_DOWN = 0x01

# Brand handling
BRAND_SPECIAL_FAN = 2
BRAND_REMAP_11 = 11
BRAND_REMAP_15 = 15

# State offsets
OFFSET_ZONE_NAMES = 104
OFFSET_ZONE_DATA = 232
OFFSET_ZONE_DAMPER = 248
OFFSET_ZONE_FEEDBACK = 296
OFFSET_SYSTEM_NAME = 383
OFFSET_AC_NAMES = 399
OFFSET_AC_STATUS = 423
OFFSET_AC_BRAND = 425
OFFSET_AC_MODE = 427
OFFSET_AC_FAN = 429
OFFSET_AC_SETPOINT = 431
OFFSET_AC_ROOM_TEMP = 433
OFFSET_AC_ERROR = 435
OFFSET_AC_UNIT_ID = 439
OFFSET_TOUCHPAD_ZONE = 443
OFFSET_TOUCHPAD_TEMP = 445
OFFSET_WIRELESS_SENSORS = 451
OFFSET_DEVICE_ID = 483

STATE_ZONE_NAME_LENGTH = 8
STATE_AC_NAME_LENGTH = 8
STATE_SYSTEM_NAME_LENGTH = 16
STATE_TOUCHPAD_COUNT = 2
STATE_ZONE_MAX = 16
STATE_SENSOR_SLOTS = 32

MIN_TEMP = 16
MAX_TEMP = 30
TEMP_STEP = 1
